### ISSUE TITLE
M1 support?

### ISSUE THREAD

**Issue by andriilive** [AudiosurfResearch/Wavebreaker-Installer#1]
Can't run the installer on M1 mac

**Comment by RubberDuckShobe** [comment]
I'll try to set up cross compilation with GitHub Actions. Can't compile/test it myself since I don't have any Apple Silicon devices (except an M1 iPad Pro but that obviously won't help)

**Comment by RubberDuckShobe** [comment]
I managed to compile an aarch64 Mac version.
Try downloading the artifact from here and tell me if it works
https://github.com/AudiosurfResearch/Wavebreaker-Installer/actions/runs/11416957152

**Comment by andriilive** [comment]
@RubberDuckShobe it's running on `15.1 (24B83)` great! I'll do a real test with a game installed somewhile next week

![CleanShot 2024-11-16 at 18 56 19@2x](https://github.com/user-attachments/assets/68339908-aeed-45dc-9cc7-97b895fe6704)

Bypassed ⚠️ **“wavebreaker-installer” is damaged and can’t be opened. You should move it to the Trash** error by:

1. Running the `sudo spctl --master-disable`

2. Lowering the allowed apps policy in system settings as shown on a screen above

![CleanShot 2024-11-16 at 19 00 25@2x](https://github.com/user-attachments/assets/4549738a-3f85-4b13-bafa-27163c9044b4)

3. Running the `xattr -c ./wavebreaker-installer.app && open ./wavebreaker-installer.app`

> **Note:** I guess it’s not necessary to complete all the above, step 2 can be enough or some kind of [brew-no-quarantine](https://houtianze.github.io/brew/mac/2020/02/18/brew-no-quarantine.html) install can be used instead

**Comment by RubberDuckShobe** [comment]
Thank you for the detailed reply! It seems to be related to signing somehow, please try this new artifact and tell me if it works: https://github.com/AudiosurfResearch/Wavebreaker-Installer/actions/runs/11872805039

**Comment by andriilive** [comment]
@RubberDuckShobe 

The new wavebreaker-installer ([macOS artifact, aarch64-apple-darwin](https://github.com/AudiosurfResearch/Wavebreaker-Installer/actions/runs/11872805039/artifacts/2197036293)) launched successfully. 

Checked both audiosurf games on steam, nor of them are compatible with aarch64 :/ damn it. Seems like a death end

**Comment by RubberDuckShobe** [comment]
Glad it worked out! I guess the game should run with a translation layer (hell, i got it to work on my Android *phone*) but that‘s out of scope for this issue/project. If there‘s any more Mac/Apple Silicon-specific problems with Wavebreaker, please feel free to open another issue.
